name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  WORKING_DIRECTORY: .
  BIN_NAME: chronicle

jobs:
  build-release:
    name: Build Release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            asset_name: chronicle-linux-amd64
          - os: macos-latest
            target: x86_64-apple-darwin
            asset_name: chronicle-darwin-amd64
          - os: macos-latest
            target: aarch64-apple-darwin
            asset_name: chronicle-darwin-arm64

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package
        shell: bash
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          mkdir -p dist/${{ matrix.asset_name }}
          cp target/${{ matrix.target }}/release/${{ env.BIN_NAME }} dist/${{ matrix.asset_name }}/
          cd dist
          tar -czf ../${{ matrix.asset_name }}.tar.gz ${{ matrix.asset_name }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.asset_name }}.tar.gz

  update-homebrew:
    name: Update Homebrew
    needs: build-release
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew Formula
        uses: mislav/bump-homebrew-formula-action@v3
        with:
          # A PR will be sent to the "homebrew-tap" repository to update this formula
          formula-name: chronicle
          formula-path: Formula/chronicle.rb
          homebrew-tap: StanleyXie/homebrew-tap
          download-url: https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/chronicle-darwin-arm64.tar.gz
          commit-message: "chore: update formula to ${{ github.ref_name }}"
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
